baseURL: 'https://devport.nl'
title: DevPort
theme: meghna-hugo
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: []
params:
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: >-
          https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  logo: images/logo.png
  description: Responsive Multipurpose Parallax Hugo Template
  author: Themefisher
  google_analytics_id: 'G-V2DFK9V5BV'
  post_share: true
  preloader:
    enable: false
    preloader: images/logo.png
  cookies:
    enable: true
    expire_days: 2
  map:
    enable: false
    gmap_api: >-
      https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  social:
    - icon: ti-facebook
      link: '#'
    - icon: ti-twitter-alt
      link: '#'
    - icon: ti-youtube
      link: '#'
    - icon: ti-linkedin
      link: '#'
    - icon: ti-dribbble
      link: '#'
    - icon: ti-pinterest
      link: '#'
Languages:
  nl:
    menu:
      main:
        - name: over ons
          url: '#about'
          weight: 1
        - name: diensten
          url: '#services'
          weight: 2
        - name: portfolio
          url: '#portfolio'
          weight: 3
        - name: team
          url: '#team'
          weight: 4
        - name: tarieven
          url: '#pricing'
          weight: 5
        - name: blog
          url: '#blog'
          weight: 6
        - name: contact
          url: '#contact'
          weight: 7
    languageName: NL
    languageCode: nl-nl
    weight: 1
    home: Home
    copyright: >-
      Copyright &copy; 2023 DevPort.nl
  en:
    menu:
      main:
        - name: about
          url: '#about'
          weight: 1
        - name: services
          url: '#services'
          weight: 2
        - name: portfolio
          url: '#portfolio'
          weight: 3
        - name: team
          url: '#team'
          weight: 4
        - name: pricing
          url: '#pricing'
          weight: 5
        - name: blog
          url: '#blog'
          weight: 6
        - name: contact
          url: '#contact'
          weight: 7
        - name: Dropdown
          weight: 7
          hasChildren: true
        - parent: Dropdown
          name: Dropdown 1
          url: '#'
          weight: 1
        - parent: Dropdown
          name: Dropdown 2
          url: '#'
          weight: 2
    languageName: EN
    languageCode: en-us
    weight: 2
    home: Home
    copyright: >-
      Copyright &copy; 2023 DevPort.nl
